### Variables
@baseUrl = https://localhost:7064/api/v1
@username = admin
@password = admin
@rememberMe = true
@bearer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjE4NjEyZjU2LWVhNzQtNDA3ZC1iZGY0LWQ4YWUzMmY2ODU1NCIsIm5iZiI6MTczMTE2Nzg3NSwiZXhwIjoxNzMxMTczMjc1LCJpYXQiOjE3MzExNjc4NzUsImlzcyI6Iklzc3VlciIsImF1ZCI6IkF1ZGllbmNlIn0.sFkIOTq0iksIsCKq13cmOdJ6O3dz2AMAyKCuQ6ne5ls

### Login Request
POST {{baseUrl}}/account/login
accept: */*
Content-Type: application/json

{
  "userName": "{{username}}",
  "password": "{{password}}",
  "rememberMe": {{rememberMe}}
}

### Get Status
GET {{baseUrl}}/account/me
accept: */*
Authorization: Bearer {{bearer_token}}
