name: Build Shield Solution

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  checks: write
  contents: write
  deployments: write
  issues: write
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  versionize:
    uses: ./.github/workflows/versionize.yml
    needs: build
  release:
    uses: ./.github/workflows/release.yml
    needs: versionize
