name: Versionize

on:
  push:
    branches:
      - main

jobs:
  versionize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Determine Changed Projects
        id: changed-projects
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          grep -E '\.csproj$' changed_files.txt > changed_projects.txt
          echo "::set-output name=projects::$(cat changed_projects.txt | tr '\n' ' ')"

      - name: Run Versionize for Each Changed Project
        run: |
          for project in ${{ steps.changed-projects.outputs.projects }}; do
            versionize --proj-name $(basename $project .csproj)
          done
